import * as THREE from 'three';
const $=s=>document.querySelector(s),canvas=$('#game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8bc3ed);scene.fog=new THREE.FogExp2(0xa7c6d9,.0007);const cam=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,3500);scene.add(new THREE.HemisphereLight(0xd8efff,0x3c4937,2.2));const sun=new THREE.DirectionalLight(0xfff0d0,3.5);sun.position.set(100,150,80);sun.castShadow=true;scene.add(sun);
// Road centre line extracted from the Road2 geometry in the supplied highway-battle GLB.
const raw=[[576.7,.2,12.3],[572.4,.2,95.3],[513.8,.1,194.2],[385.9,.2,290],[313.3,-.9,350.3],[231.1,-1.2,398.6],[111.6,-1.2,475.6],[33.2,-.9,527.4],[-41.5,2.4,576.8],[-132.2,4.8,624.5],[-225.3,5,622.3],[-297.1,5,576.4],[-360.1,5,508.7],[-382,4.1,425],[-354.8,1.7,322.6],[-314.7,.2,205.6],[-269.4,.2,73.6],[-229,.2,-43.9],[-204.8,.2,-114.1],[-189.3,.2,-177],[-193.8,.2,-234],[-216.9,.2,-285.9],[-250.1,.2,-377.5],[-244.3,.1,-493.5],[-168.6,.2,-610.4],[-63.8,.2,-727.8],[5.8,.2,-785.9],[52.1,.2,-801],[141.6,.2,-792],[250.7,.2,-738.4],[333.1,.2,-670.9],[401.4,.2,-578.1],[470.3,.2,-475.4],[511,.2,-413.3],[530.3,.2,-376.5],[542.3,.2,-345.4],[561.8,.2,-283.1],[576.1,.2,-194.2],[576.7,.2,-86.7]],pts=raw.map(v=>new THREE.Vector3(...v)),curve=new THREE.CatmullRomCurve3(pts,true,'centripetal'),N=600,W=7.2,C=[];let v=[],ix=[];
for(let i=0;i<=N;i++){let t=i/N,p=curve.getPointAt(t),d=curve.getTangentAt(t).normalize(),s=new THREE.Vector3(-d.z,0,d.x).normalize();C.push(p);for(let q of [-W,W]){let a=p.clone().addScaledVector(s,q);v.push(a.x,a.y,a.z)}}for(let i=0;i<N;i++){let a=i*2;ix.push(a,a+2,a+1,a+1,a+2,a+3)}let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(ix);g.computeVertexNormals();let road=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x363b40,roughness:.95}));road.receiveShadow=true;scene.add(road);
for(let side of [-1,1]){let p=[];for(let i=0;i<N;i+=3){let t=i/N,c=C[i],d=curve.getTangentAt(t).normalize(),s=new THREE.Vector3(-d.z,0,d.x).normalize();p.push(c.clone().addScaledVector(s,side*(W+.5)).add(new THREE.Vector3(0,.4,0)))}scene.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(p,true),300,.12,5,true),new THREE.MeshStandardMaterial({color:0xd5d9dc,metalness:.7})))}
let ground=new THREE.Mesh(new THREE.CircleGeometry(1700,48),new THREE.MeshStandardMaterial({color:0x536f49,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-2;scene.add(ground);
const car=new THREE.Group();scene.add(car);let body=new THREE.Mesh(new THREE.BoxGeometry(1.55,.4,3.8),new THREE.MeshStandardMaterial({color:0x173b72,metalness:.5,roughness:.3}));body.position.y=.5;body.castShadow=true;car.add(body);let wing=new THREE.Mesh(new THREE.BoxGeometry(1.9,.08,.5),new THREE.MeshStandardMaterial({color:0xd21e2b}));wing.position.set(0,.45,1.7);car.add(wing);const wheels=[];for(let [x,z,f] of [[-.8,1.2,1],[.8,1.2,1],[-.8,-1.25,0],[.8,-1.25,0]]){let p=new THREE.Group();p.position.set(x,.38,z);car.add(p);let w=new THREE.Mesh(new THREE.CylinderGeometry(.37,.37,.25,18),new THREE.MeshStandardMaterial({color:0x050505}));w.rotation.z=Math.PI/2;p.add(w);wheels.push([p,w,f])}
let speed=0,steer=0,near=0,last=performance.now(),keys={},touch={throttle:0,brake:0,left:0,right:0},cfg={maxSpeed:360,grip:1,downforce:1,camera:'chase',weather:'clear',time:'day'};function reset(){near=0;let p=C[0],d=curve.getTangentAt(0);car.position.copy(p).add(new THREE.Vector3(0,.42,0));car.rotation.y=Math.atan2(d.x,d.z);speed=0}reset();
function closest(){let b=1e9,bi=near;for(let k=-18;k<=18;k++){let i=(near+k+N)%N,d=car.position.distanceToSquared(C[i]);if(d<b){b=d;bi=i}}near=bi;return [Math.sqrt(b),C[bi]]}
function step(dt){let th=keys.KeyW||keys.ArrowUp||touch.throttle,br=keys.KeyS||keys.ArrowDown||keys.Space||touch.brake,l=keys.KeyA||keys.ArrowLeft||touch.left,r=keys.KeyD||keys.ArrowRight||touch.right;if(th)speed+=21*dt;if(br)speed-=speed>1?35*dt:10*dt;speed-=Math.sign(speed)*Math.min(Math.abs(speed),(.35+.0018*speed*speed)*dt);speed=THREE.MathUtils.clamp(speed,-14,cfg.maxSpeed/3.6);steer=THREE.MathUtils.damp(steer,(l?1:0)-(r?1:0),8,dt);let wet=cfg.weather==='rain'?.7:cfg.weather==='snow'?.45:1;car.rotation.y+=steer*.55*THREE.MathUtils.clamp(Math.abs(speed)/8,0,1)*cfg.grip*wet*dt*Math.sign(speed||1);car.position.x+=Math.sin(car.rotation.y)*speed*dt;car.position.z+=Math.cos(car.rotation.y)*speed*dt;let [dist,p]=closest();if(dist>W-1){speed*=.97;if(dist>W+.7){let q=p.clone().sub(car.position);q.y=0;car.position.addScaledVector(q.normalize(),Math.min(2,dist-W));speed*=-.25}}car.position.y=THREE.MathUtils.damp(car.position.y,p.y+.42,14,dt)-Math.min(speed*speed*.00003*cfg.downforce,.05);for(let [p,w,f] of wheels){if(f)p.rotation.y=-steer*.45;w.rotation.x-=speed*dt/.37}$('#speed').textContent=Math.round(Math.abs(speed)*3.6);$('#gear').textContent=speed>2?'D':speed<-1?'R':'N';$('#rpm').style.width=Math.min(100,18+Math.abs(speed)*1.1)+'%'}
const cameras={chase:[0,3,-9],close:[0,2,-6],tv:[4.5,2.5,-7],cockpit:[0,1,.2],nose:[0,.55,2.2],top:[0,12,-3]};function view(dt){let a=cameras[cfg.camera]||cameras.chase,q=new THREE.Vector3(...a).applyAxisAngle(new THREE.Vector3(0,1,0),car.rotation.y);cam.position.lerp(car.position.clone().add(q),1-Math.exp(-7*dt));let f=new THREE.Vector3(Math.sin(car.rotation.y),0,Math.cos(car.rotation.y));cam.lookAt(car.position.clone().addScaledVector(f,cfg.camera==='nose'?10:4).add(new THREE.Vector3(0,.6,0)))}
function conditions(){let night=cfg.time==='night',sunset=cfg.time==='sunset';scene.background.set(night?0x050b18:sunset?0xe58d67:0x8bc3ed);sun.intensity=night?.35:sunset?2:3.5;scene.fog.color.set(cfg.weather==='fog'?0x9aa5aa:night?0x111827:0xa7c6d9);scene.fog.density=cfg.weather==='fog'?.004:cfg.weather==='rain'?.0014:.0007;$('#surface').textContent=cfg.weather.toUpperCase()}
function loop(t){let dt=Math.min((t-last)/1000,.033);last=t;step(dt);view(dt);renderer.render(scene,cam);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyR')reset();if(e.code==='Escape')$('#settings').showModal()});addEventListener('keyup',e=>keys[e.code]=0);addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.querySelectorAll('[data-control]').forEach(b=>{let k=b.dataset.control,set=x=>{touch[k]=x;b.classList.toggle('pressed',!!x)};b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(1)};b.onpointerup=b.onpointercancel=()=>set(0)});$('#reset').onclick=reset;$('#menu').onclick=()=>$('#settings').showModal();$('#close-settings').onclick=$('#resume').onclick=()=>$('#settings').close();$('#reset-start').onclick=reset;$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
for(let id of ['camera','weather','time'])$('#'+id).onchange=e=>{cfg[id]=e.target.value;if(id!=='camera')conditions();$('#camera-name').textContent=cfg.camera.toUpperCase()};for(let [id,key] of [['maxSpeed','maxSpeed'],['grip','grip'],['downforce','downforce']]){let e=$('#'+id);cfg[key]=+e.value;e.oninput=()=>{cfg[key]=+e.value;$('#'+id+'-value').textContent=id==='maxSpeed'?e.value+' km/h':e.value+'×'}}
$('#start').disabled=false;$('#start').textContent='Start driving';$('#load-message').textContent='Preview ready.';$('#start').onclick=()=>{$('#loading').hidden=true;$('#hud').hidden=false};conditions();requestAnimationFrame(loop);